### ISSUE TITLE
无法运行问题

### ISSUE THREAD

**Issue by Polaris-zmy** [duowuyms/NetLLM#6]
大佬看下面这个报错显示无法从huggingface_hub中导入split_torch_state_dict_into_shards。我也更新了这个库，搞了好久一直是这个错误，请问这是咋回事呀？
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1282, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/root/miniconda3/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 84, in <module>
    from accelerate.hooks import AlignDevicesHook, add_hook_to_module
  File "/root/miniconda3/lib/python3.10/site-packages/accelerate/__init__.py", line 16, in <module>
    from .accelerator import Accelerator
  File "/root/miniconda3/lib/python3.10/site-packages/accelerate/accelerator.py", line 34, in <module>
    from huggingface_hub import split_torch_state_dict_into_shards
ImportError: cannot import name 'split_torch_state_dict_into_shards' from 'huggingface_hub' (/root/miniconda3/lib/python3.10/site-packages/huggingface_hub/__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/autodl-fs/data/NetLLM/viewport_prediction/run_plm.py", line 14, in <module>
    from utils.plms_utils import load_plm
  File "/autodl-fs/data/NetLLM/viewport_prediction/utils/plms_utils.py", line 11, in <module>
    from openprompt.utils.logging import logger
  File "/root/miniconda3/lib/python3.10/site-packages/openprompt/__init__.py", line 2, in <module>
    from .pipeline_base import PromptDataLoader, PromptModel, PromptForClassification, PromptForGeneration
  File "/root/miniconda3/lib/python3.10/site-packages/openprompt/pipeline_base.py", line 4, in <module>
    from transformers.generation_utils import GenerationMixin
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/generation_utils.py", line 19, in <module>
    from .generation import GenerationMixin
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1272, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1284, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.generation.utils because of the following error (look up to see its traceback):
cannot import name 'split_torch_state_dict_into_shards' from 'huggingface_hub' (/root/miniconda3/lib/python3.10/site-packages/huggingface_hub/__init__.py)

**Comment by NanQiao1106** [comment]
huggingface_hub版本问题
